# Kubernetes resource manifests for deploying the Simulator service

# NAMESPACE
---
apiVersion: v1
kind: Namespace
metadata:
  name: flapflap

# DEPLOYMENT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
  namespace: flapflap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          imagePullPolicy: Never
          image: flapflapio/simulator:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "0"
              cpu: "0"
          ports:
            - containerPort: 8080

# SERVICE
---
apiVersion: v1
kind: Service
metadata:
  name: simulator-service
  namespace: flapflap
spec:
  selector:
    app: simulator
  ports:
    - port: 8080
      targetPort: 8080

# INGRESS
# Add to your /etc/hosts: '192.168.49.2 api.flapflap.io'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulator-ingress
  namespace: flapflap
  labels:
    name: simulator-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: $1$2
spec:
  rules:
    - host: api.flapflap.io
      http:
        paths:
          - pathType: Prefix
            path: "/simulator(/|$)(.*)"
            backend:
              service:
                name: simulator-service
                port:
                  number: 8080
