name: Update GitHub Packages, deploy to AWS

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        required: false
        description: "Test scenario tags"

env:
  APP_VERSION: 0.1.0
  CHART_NAME: simulator
  NAMESPACE: flapflap

jobs:
  push:
    name: GitHub Packages Update
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Set image tag
        run: echo "TAG=${GITHUB_REF_NAME}-${APP_VERSION}-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u flapflapio --password-stdin

      - name: Build image
        run: make docker

      - name: Push image
        run: make docker-push

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: push
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Set image tag
        run: echo "TAG=${GITHUB_REF_NAME}-${APP_VERSION}-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Create KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG_FILE }}" >> kubeconfig.yml
          chmod 0600 kubeconfig.yml
          echo "KUBECONFIG=$(realpath kubeconfig.yml)" >> $GITHUB_ENV

      - name: Download Helm
        run: |
          wget https://get.helm.sh/helm-v3.8.0-rc.1-linux-amd64.tar.gz
          tar -xvzf helm*.tar.gz
          mv linux*/helm ./
          set -ex
          ./helm version
          ./helm list --all-namespaces
          set +ex

      - name: Deploy chart
        run: |
          set -ex
          helm upgrade \
            --namespace "$NAMESPACE" \
            --install \
            --atomic \
            --wait \
            --timeout '360s' \
            --set imageTag="$TAG" \
            "$CHART_NAME" \
            ./kubernetes/simulator-chart
